version: '3'
services:
  db:
    container_name: database
    image: mysql:latest
    ports:
      - "3302:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    restart: always
  web:
    container_name: app
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "
              python3 manage.py makemigrations
              && python3 manage.py migrate
              && python3 manage.py runserver 0.0.0.0:8000
              "
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db